/**
 * Node Registry — auto-discovers all nodes from the nodes/ directory.
 *
 * At build time (or import time), this module imports every node's handler
 * and reads its config. The registry is the single source of truth for
 * what nodes are available in the system.
 *
 * For Vercel Edge deployment, we use static imports (generated by
 * generate-registry.ts) since dynamic fs access isn't available at runtime.
 */

import type { NodeConfig, NodeHandler, RegisteredNode } from "./types.js";
import { createRequire } from "module";

const require = createRequire(import.meta.url);

// ── Static handler imports (generated — do not edit between markers) ────────
// __REGISTRY_START__
import httpRequestHandler from "../../nodes/http-request/index.js";
import twilioSmsHandler from "../../nodes/twilio-sms/index.js";
import googlePlacesLookupHandler from "../../nodes/google-places-lookup/index.js";
import grokPromptHandler from "../../nodes/grok-prompt/index.js";
import slackPostHandler from "../../nodes/slack-post/index.js";
import discordSendHandler from "../../nodes/discord-send/index.js";
import supabaseQueryHandler from "../../nodes/supabase-query/index.js";
import webhookTriggerHandler from "../../nodes/webhook-trigger/index.js";
// __REGISTRY_END__

// ── Load configs via require (resolveJsonModule) ────────────────────────────

const httpRequestConfig = require("../../nodes/http-request/config.json") as NodeConfig;
const twilioSmsConfig = require("../../nodes/twilio-sms/config.json") as NodeConfig;
const googlePlacesLookupConfig = require("../../nodes/google-places-lookup/config.json") as NodeConfig;
const grokPromptConfig = require("../../nodes/grok-prompt/config.json") as NodeConfig;
const slackPostConfig = require("../../nodes/slack-post/config.json") as NodeConfig;
const discordSendConfig = require("../../nodes/discord-send/config.json") as NodeConfig;
const supabaseQueryConfig = require("../../nodes/supabase-query/config.json") as NodeConfig;
const webhookTriggerConfig = require("../../nodes/webhook-trigger/config.json") as NodeConfig;

// ── Registry map ────────────────────────────────────────────────────────────

const registry = new Map<string, RegisteredNode>();

function register(config: NodeConfig, handler: NodeHandler) {
  registry.set(config.name, { config, handler });
}

// Register all imported nodes
register(httpRequestConfig, httpRequestHandler);
register(twilioSmsConfig, twilioSmsHandler);
register(googlePlacesLookupConfig, googlePlacesLookupHandler);
register(grokPromptConfig, grokPromptHandler);
register(slackPostConfig, slackPostHandler);
register(discordSendConfig, discordSendHandler);
register(supabaseQueryConfig, supabaseQueryHandler);
register(webhookTriggerConfig, webhookTriggerHandler);

// ── Public API ──────────────────────────────────────────────────────────────

export function getNode(name: string): RegisteredNode | undefined {
  return registry.get(name);
}

export function getAllNodes(): RegisteredNode[] {
  return Array.from(registry.values());
}

export function getNodeConfigs(): NodeConfig[] {
  return getAllNodes().map((n) => n.config);
}

export function listNodeSummaries(): { name: string; displayName: string; description: string; category: string; icon: string }[] {
  return getNodeConfigs().map((c) => ({
    name: c.name,
    displayName: c.displayName,
    description: c.description,
    category: c.category,
    icon: c.icon,
  }));
}
