/**
 * Node Registry — auto-discovers all nodes from the nodes/ directory.
 *
 * Static imports are generated by generate-registry.ts. Run
 * `npm run generate-registry` after adding or removing nodes.
 */

import type { NodeConfig, NodeHandler, RegisteredNode } from "./types";

// ── Static handler imports (generated — do not edit between markers) ────────
// __REGISTRY_START__
import discordSendHandler from "../../nodes/discord-send/index";
import googlePlacesLookupHandler from "../../nodes/google-places-lookup/index";
import grokPromptHandler from "../../nodes/grok-prompt/index";
import httpRequestHandler from "../../nodes/http-request/index";
import slackPostHandler from "../../nodes/slack-post/index";
import supabaseQueryHandler from "../../nodes/supabase-query/index";
import twilioSmsHandler from "../../nodes/twilio-sms/index";
import webhookTriggerHandler from "../../nodes/webhook-trigger/index";
// __REGISTRY_END__

// ── Load configs ────────────────────────────────────────────────────────────
// __CONFIGS_START__
import discordSendConfig from "../../nodes/discord-send/config.json";
import googlePlacesLookupConfig from "../../nodes/google-places-lookup/config.json";
import grokPromptConfig from "../../nodes/grok-prompt/config.json";
import httpRequestConfig from "../../nodes/http-request/config.json";
import slackPostConfig from "../../nodes/slack-post/config.json";
import supabaseQueryConfig from "../../nodes/supabase-query/config.json";
import twilioSmsConfig from "../../nodes/twilio-sms/config.json";
import webhookTriggerConfig from "../../nodes/webhook-trigger/config.json";
// __CONFIGS_END__

// ── Registry map ────────────────────────────────────────────────────────────

const registry = new Map<string, RegisteredNode>();

function register(config: NodeConfig, handler: NodeHandler) {
  registry.set(config.name, { config, handler });
}

// __REGISTER_START__
register(discordSendConfig as NodeConfig, discordSendHandler);
register(googlePlacesLookupConfig as NodeConfig, googlePlacesLookupHandler);
register(grokPromptConfig as NodeConfig, grokPromptHandler);
register(httpRequestConfig as NodeConfig, httpRequestHandler);
register(slackPostConfig as NodeConfig, slackPostHandler);
register(supabaseQueryConfig as NodeConfig, supabaseQueryHandler);
register(twilioSmsConfig as NodeConfig, twilioSmsHandler);
register(webhookTriggerConfig as NodeConfig, webhookTriggerHandler);
// __REGISTER_END__

// ── Public API ──────────────────────────────────────────────────────────────

export function getNode(name: string): RegisteredNode | undefined {
  return registry.get(name);
}

export function getAllNodes(): RegisteredNode[] {
  return Array.from(registry.values());
}

export function getNodeConfigs(): NodeConfig[] {
  return getAllNodes().map((n) => n.config);
}

export function listNodeSummaries(): { name: string; displayName: string; description: string; category: string; icon: string }[] {
  return getNodeConfigs().map((c) => ({
    name: c.name,
    displayName: c.displayName,
    description: c.description,
    category: c.category,
    icon: c.icon,
  }));
}
